// backend/src/shared/types/organismos.ts

export interface OrganismoInciso {
  codigo: number;
  nombre: string;
  tipo: TipoOrganismo;
}

export enum TipoOrganismo {
  PODER_EJECUTIVO = 'Poder Ejecutivo',
  PODER_LEGISLATIVO = 'Poder Legislativo',
  PODER_JUDICIAL = 'Poder Judicial',
  ORGANISMO_AUTONOMO = 'Organismo Autónomo',
  ENTE_AUTONOMO = 'Ente Autónomo',
  INTENDENCIA = 'Intendencia',
  OTRO = 'Otro',
}

// Mapa completo de los 99 incisos reales del SICE
export const ORGANISMOS_INCISO: Record<number, OrganismoInciso> = {
  1:  { codigo: 1,  nombre: 'Poder Legislativo', tipo: TipoOrganismo.PODER_LEGISLATIVO },
  2:  { codigo: 2,  nombre: 'Presidencia de la República', tipo: TipoOrganismo.PODER_EJECUTIVO },
  3:  { codigo: 3,  nombre: 'Ministerio de Defensa Nacional', tipo: TipoOrganismo.PODER_EJECUTIVO },
  4:  { codigo: 4,  nombre: 'Ministerio del Interior', tipo: TipoOrganismo.PODER_EJECUTIVO },
  5:  { codigo: 5,  nombre: 'Ministerio de Economía y Finanzas', tipo: TipoOrganismo.PODER_EJECUTIVO },
  6:  { codigo: 6,  nombre: 'Ministerio de Relaciones Exteriores', tipo: TipoOrganismo.PODER_EJECUTIVO },
  7:  { codigo: 7,  nombre: 'Ministerio de Ganadería, Agricultura y Pesca', tipo: TipoOrganismo.PODER_EJECUTIVO },
  8:  { codigo: 8,  nombre: 'Ministerio de Industria, Energía y Minería', tipo: TipoOrganismo.PODER_EJECUTIVO },
  9:  { codigo: 9,  nombre: 'Ministerio de Turismo', tipo: TipoOrganismo.PODER_EJECUTIVO },
  10: { codigo: 10, nombre: 'Ministerio de Transporte y Obras Públicas', tipo: TipoOrganismo.PODER_EJECUTIVO },
  11: { codigo: 11, nombre: 'Ministerio de Educación y Cultura', tipo: TipoOrganismo.PODER_EJECUTIVO },
  12: { codigo: 12, nombre: 'Ministerio de Salud Pública', tipo: TipoOrganismo.PODER_EJECUTIVO },
  13: { codigo: 13, nombre: 'Ministerio de Trabajo y Seguridad Social', tipo: TipoOrganismo.PODER_EJECUTIVO },
  14: { codigo: 14, nombre: 'Ministerio de Vivienda y Ordenamiento Territorial', tipo: TipoOrganismo.PODER_EJECUTIVO },
  15: { codigo: 15, nombre: 'Ministerio de Desarrollo Social', tipo: TipoOrganismo.PODER_EJECUTIVO },
  16: { codigo: 16, nombre: 'Poder Judicial', tipo: TipoOrganismo.PODER_JUDICIAL },
  17: { codigo: 17, nombre: 'Tribunal de Cuentas', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  18: { codigo: 18, nombre: 'Corte Electoral', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  19: { codigo: 19, nombre: 'Tribunal de lo Contencioso Administrativo', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  24: { codigo: 24, nombre: 'Diversos Créditos', tipo: TipoOrganismo.OTRO },
  25: { codigo: 25, nombre: 'Administración Nacional de Educación Pública', tipo: TipoOrganismo.ENTE_AUTONOMO },
  26: { codigo: 26, nombre: 'Universidad de la República', tipo: TipoOrganismo.ENTE_AUTONOMO },
  27: { codigo: 27, nombre: 'Instituto del Niño y Adolescente del Uruguay', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  28: { codigo: 28, nombre: 'Banco de Previsión Social', tipo: TipoOrganismo.ENTE_AUTONOMO },
  29: { codigo: 29, nombre: 'Administración de Servicios de Salud del Estado', tipo: TipoOrganismo.ENTE_AUTONOMO },
  30: { codigo: 30, nombre: 'Deuda Pública', tipo: TipoOrganismo.OTRO },
  31: { codigo: 31, nombre: 'Universidad Tecnológica del Uruguay', tipo: TipoOrganismo.ENTE_AUTONOMO },
  32: { codigo: 32, nombre: 'Instituto Uruguayo de Meteorología', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  33: { codigo: 33, nombre: 'Fiscalía General de la Nación', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  34: { codigo: 34, nombre: 'Junta de Transparencia y Ética Pública', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  35: { codigo: 35, nombre: 'Instituto Nacional de Inclusión Social Adolescente', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  36: { codigo: 36, nombre: 'Ministerio de Ambiente', tipo: TipoOrganismo.PODER_EJECUTIVO },
  40: { codigo: 40, nombre: 'Instituciones sin fines de lucro públicas', tipo: TipoOrganismo.OTRO },
  47: { codigo: 47, nombre: 'Cajas paraestatales', tipo: TipoOrganismo.OTRO },
  50: { codigo: 50, nombre: 'Banco Central del Uruguay', tipo: TipoOrganismo.ENTE_AUTONOMO },
  51: { codigo: 51, nombre: 'Banco de la República Oriental del Uruguay', tipo: TipoOrganismo.ENTE_AUTONOMO },
  52: { codigo: 52, nombre: 'Banco Hipotecario del Uruguay', tipo: TipoOrganismo.ENTE_AUTONOMO },
  53: { codigo: 53, nombre: 'Banco de Seguros del Estado', tipo: TipoOrganismo.ENTE_AUTONOMO },
  59: { codigo: 59, nombre: 'Organismos Financieros Internacionales', tipo: TipoOrganismo.OTRO },
  60: { codigo: 60, nombre: 'Administración Nacional de Combustible, Alcohol y Portland', tipo: TipoOrganismo.ENTE_AUTONOMO },
  61: { codigo: 61, nombre: 'Administración Nacional de Usinas y Trasmisiones Eléctricas', tipo: TipoOrganismo.ENTE_AUTONOMO },
  62: { codigo: 62, nombre: 'Administración de los Ferrocarriles del Estado', tipo: TipoOrganismo.ENTE_AUTONOMO },
  63: { codigo: 63, nombre: 'Primera Líneas Uruguayas de Navegación Aérea', tipo: TipoOrganismo.ENTE_AUTONOMO },
  64: { codigo: 64, nombre: 'Administración Nacional de Puertos', tipo: TipoOrganismo.ENTE_AUTONOMO },
  65: { codigo: 65, nombre: 'Administración Nacional de Telecomunicaciones', tipo: TipoOrganismo.ENTE_AUTONOMO },
  66: { codigo: 66, nombre: 'Administración de las Obras Sanitarias del Estado', tipo: TipoOrganismo.ENTE_AUTONOMO },
  67: { codigo: 67, nombre: 'Administración Nacional de Correos', tipo: TipoOrganismo.ENTE_AUTONOMO },
  68: { codigo: 68, nombre: 'Agencia Nacional de Vivienda', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  69: { codigo: 69, nombre: 'Unidad Reguladora de Servicios de Energía y Agua', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  70: { codigo: 70, nombre: 'Instituto Nacional de Colonización', tipo: TipoOrganismo.ENTE_AUTONOMO },
  71: { codigo: 71, nombre: 'Unidad Reguladora de Servicios de Comunicaciones', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  72: { codigo: 72, nombre: 'Instituto Nacional de Carnes', tipo: TipoOrganismo.ORGANISMO_AUTONOMO },
  79: { codigo: 79, nombre: 'Intendencias Municipales (sin discriminar)', tipo: TipoOrganismo.INTENDENCIA },
  80: { codigo: 80, nombre: 'Intendencia de Artigas', tipo: TipoOrganismo.INTENDENCIA },
  81: { codigo: 81, nombre: 'Intendencia de Canelones', tipo: TipoOrganismo.INTENDENCIA },
  82: { codigo: 82, nombre: 'Intendencia de Cerro Largo', tipo: TipoOrganismo.INTENDENCIA },
  83: { codigo: 83, nombre: 'Intendencia de Colonia', tipo: TipoOrganismo.INTENDENCIA },
  84: { codigo: 84, nombre: 'Intendencia de Durazno', tipo: TipoOrganismo.INTENDENCIA },
  85: { codigo: 85, nombre: 'Intendencia de Flores', tipo: TipoOrganismo.INTENDENCIA },
  86: { codigo: 86, nombre: 'Intendencia de Florida', tipo: TipoOrganismo.INTENDENCIA },
  87: { codigo: 87, nombre: 'Intendencia de Lavalleja', tipo: TipoOrganismo.INTENDENCIA },
  88: { codigo: 88, nombre: 'Intendencia de Maldonado', tipo: TipoOrganismo.INTENDENCIA },
  89: { codigo: 89, nombre: 'Intendencia de Paysandú', tipo: TipoOrganismo.INTENDENCIA },
  90: { codigo: 90, nombre: 'Intendencia de Río Negro', tipo: TipoOrganismo.INTENDENCIA },
  91: { codigo: 91, nombre: 'Intendencia de Rivera', tipo: TipoOrganismo.INTENDENCIA },
  92: { codigo: 92, nombre: 'Intendencia de Rocha', tipo: TipoOrganismo.INTENDENCIA },
  93: { codigo: 93, nombre: 'Intendencia de Salto', tipo: TipoOrganismo.INTENDENCIA },
  94: { codigo: 94, nombre: 'Intendencia de San José', tipo: TipoOrganismo.INTENDENCIA },
  95: { codigo: 95, nombre: 'Intendencia de Soriano', tipo: TipoOrganismo.INTENDENCIA },
  96: { codigo: 96, nombre: 'Intendencia de Tacuarembó', tipo: TipoOrganismo.INTENDENCIA },
  97: { codigo: 97, nombre: 'Intendencia de Treinta y Tres', tipo: TipoOrganismo.INTENDENCIA },
  98: { codigo: 98, nombre: 'Intendencia de Montevideo', tipo: TipoOrganismo.INTENDENCIA },
  99: { codigo: 99, nombre: 'Congreso de Intendentes', tipo: TipoOrganismo.INTENDENCIA },
};